#!/bin/bash


##### NO CONFIGURATION NECESSARY.

MY_PATH="$( cd -P "$( dirname "$0" )" && pwd )"

MY_API_KEY=`cat $MY_PATH/.key 2>/dev/null`

MY_DOMAIN_ID=`cat $MY_PATH/.domain 2>/dev/null`

MY_RESOURCE_ID=`cat $MY_PATH/.resource 2>/dev/null`

LOG_FILE="$MY_PATH/dns.log"

CACHED_IP_FILE="$MY_PATH/.ip"

LINODE_API_URL="https://api.linode.com/?api_key=$MY_API_KEY"



##### IP FUNCTIONS

function get_ip {
  local IP=`curl --silent http://checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`
  [ "$IP" == "" ] && {
    echo "[`date`] dyndns lookup failed, checking whatismyipaddress..." >> $LOG_FILE
    IP=`curl --silent http://bot.whatismyipaddress.com`
  }
  [ "$IP" == "" ] && {
    echo "[`date`] whatismyipaddress lookup failed, giving up." >> $LOG_FILE
    exit 1;
  }
  echo $IP
}

function get_cached_ip {
  cat $CACHED_IP_FILE 2>/dev/null
}



##### LINODE API HELPERS

# Retrieves a list of domains in your linode DNS manager.
function list_domains {
  echo $(curl --silent $LINODE_API_URL\&api_action=domain.list) | python -mjson.tool
}

# Retrieves a list of resources (i.e. subdomains) for a particular domain.
# @param Domain ID
function list_resources {
  [ $# -ne 1 ] && {
      echo "Usage: list_resources domain" 1>&2;
      exit 1;
  }
  echo $(curl --silent $LINODE_API_URL\&api_action=domain.resource.list\&DomainID=$1) | python -mjson.tool
}

# Updates a domain resource.
# @param Domain ID
# @param Resource ID
function update_resource_target {
  [ $# -ne 2 ] && {
      echo "Usage: update_resource_target domain resource" 1>&2;
      exit 1;
  }
  echo $(curl --silent -g $LINODE_API_URL\&api_action=domain.resource.update\&DomainID=$1\&ResourceID=$2\&TTL_sec=300\&Target=[remote_addr])
}

function update {
  IP_OLD=`get_cached_ip`
  IP_NEW=`get_ip`

  [ "$IP_OLD" != "$IP_NEW" ] && [ "$IP_NEW" != "" ] && {
    update_resource_target $MY_DOMAIN_ID $MY_RESOURCE_ID
    echo "[`date`] IP changed from $IP_OLD to $IP_NEW" >> $LOG_FILE
  }

  [ "$IP_NEW" != "" ] && {
    echo $IP_NEW > $CACHED_IP_FILE
  }
}



##### DO IT

$@
exit 0;
